### ISSUE TITLE
Error logs scope base

### ISSUE THREAD

**Issue by bremen90** [MeteorTheLizard/MMM_M9k_Remastered#10]
I have this error in the logs

addons/M9k_Remastered/lua/weapons/bobs_scoped_base.lua:170: attempt to index local 'vmAttachment' (a nil value)
 1. unknown - addons/M9k_Remastered/lua/weapons/bobs_scoped_base.lua:170

**Comment by MeteorTheLizard** [comment]
Fixed. https://github.com/MeteorTheLizard/MMM_M9k_Remastered/commit/c9a63bcf48c93ee082d01aa445cb8e1758174339

Thank you for the bug report.
