### ISSUE TITLE
Error log shotty base

### ISSUE THREAD

**Issue by bremen90** [MeteorTheLizard/MMM_M9k_Remastered#11]
I have this error in my logs

addons/M9k_Remastered/lua/weapons/bobs_shotty_base.lua:110: attempt to concatenate field 'OurIndex' (a nil value)
  1. unknown - addons/M9k_Remastered/lua/weapons/bobs_shotty_base.lua:110

**Comment by MeteorTheLizard** [comment]
Please post the full error message.

**Comment by bremen90** [comment]
hmmm that's the only thing that left the error log
I will wait longer to see if I can replicate it

**Comment by wrefgtzweve** [comment]
Had the exact same same, clientside error

[M9k Remastered] lua/weapons/bobs_shotty_base.lua:110: attempt to concatenate field 'OurIndex' (a nil value)
  1. unknown - lua/weapons/bobs_shotty_base.lua:110

**Comment by MeteorTheLizard** [comment]
The issue should now be resolved. Thanks for your report.
