### ISSUE TITLE
Bug: Reloading while scoping makes the scope toggle for non toggle weapons

### ISSUE THREAD

**Issue by wrefgtzweve** [MeteorTheLizard/MMM_M9k_Remastered#13]
How to replicate
1. Get the m9k_mp9
2. Shoot once
3. Hold down scope and reload
4. Release scope

You'll still be scoping after, easy fix is just to click right click again. It's not a major bug or anything but it doesn't seem intended.

**Comment by MeteorTheLizard** [comment]
Does this happen in Singleplayer or Multiplayer?

**Comment by wrefgtzweve** [comment]
Happened in a local server, however i can't seem to get it to replicate it on a public server for some reason

**Comment by MeteorTheLizard** [comment]
There is a big difference between Singleplayer and Multiplayer. That's why this addon used to be Multiplayer only at the beginning.

I'm unable to replicate this issue in both Singleplayer and Multiplayer.

**Comment by wrefgtzweve** [comment]
I'll give it a shot again, wierd that it stopped happening.

**Comment by wrefgtzweve** [comment]
Well for some reason it's not happening anymore, didn't change anything in my game from when i had the issue yesterday
