### ISSUE TITLE
BUG: Scoping & Reloading at the same time causes stuck scope

### ISSUE THREAD

**Issue by wrefgtzweve** [MeteorTheLizard/MMM_M9k_Remastered#16]
When you reload while scoping scoping will become stuck and you can't unscope anymore till the reload is over

**Comment by MeteorTheLizard** [comment]
https://github.com/MeteorTheLizard/MMM_M9k_Remastered/commit/9ca37c0a4e3a7d679df988ddf5bed217026eaf71

Fixed in live. If the issue persists, please open a new issue. Thank you for your report.
