### ISSUE TITLE
Proximity mines position doesn't update

### ISSUE THREAD

**Issue by wrefgtzweve** [MeteorTheLizard/MMM_M9k_Remastered#19]
when a proxy mine is placed in the air and moved the detection and explosion position stay at the place it was originally placed
https://github.com/MeteorTheLizard/MMM_M9k_Remastered/blob/master/lua/entities/m9k_proxy.lua#L20
resulting in the bomb visually not being anywhere near the explosion

**Comment by MeteorTheLizard** [comment]
Thank you for the report. This will be fixed with the next update.
