### ISSUE TITLE
Bug: Incorrect kill icons on some weapons.

### ISSUE THREAD

**Issue by wrefgtzweve** [MeteorTheLizard/MMM_M9k_Remastered#22]
A after some testing https://github.com/code-Toby and me noticed that some m9k weapons show no kill icon or kill icons from the wrong weapon, these are the following we could find that have this issue:

`m9k_nitro`
`m9k_ex41`
`m9k_milkormgl`
`m9k_matador`
`m9k_rpg7`
`m9k_usc`

Examples:
![image](https://user-images.githubusercontent.com/69946827/137604057-b72cf13b-0ae5-460d-96ec-29b18e4989cb.png)
![image](https://user-images.githubusercontent.com/69946827/137604084-7ac9d3ab-878e-4f9f-90ef-773ee4bba910.png)

**Comment by MeteorTheLizard** [comment]
Killicons automatically use .vtf files that share the same class name and are in a specific folder within the materials folder. Since material files were unchanged, this issue originates from the legacy m9k pack(s).

I will be looking into this once I have time
