### ISSUE TITLE
Recoil makes the weapon pack broken.

### ISSUE THREAD

**Issue by galaxym4n** [MeteorTheLizard/MMM_M9k_Remastered#27]
the recoil of the weapons in M9K remastered is correct in single player but not multiplayer, it's crazy high and not normal in multiplayer, im not sure how this has happened but i can show you on discord or you can test it yourself.

**Comment by MeteorTheLizard** [comment]
Make sure you don't have conflicting mods installed. This behavior was reported in the past, but I'm unable to replicate it. It works perfectly fine for me in singleplayer, and multiplayer. Regardless of gamemode as well, and it works as expected on low or high tickrate servers as well. This makes me think that this is a mod conflict.

**Comment by galaxym4n** [comment]
I've actually tested with plain DarkRP servers on single player, and multi player. I can show you on discord if you like as I don't have a recording software.
