### ISSUE TITLE
physgun!

### ISSUE THREAD

**Issue by Spartakingdom** [MeteorTheLizard/MMM_M9k_Remastered#28]
The addon is not loading on the physgun host!

**Comment by MeteorTheLizard** [comment]
Take the issue to them then.

**Comment by Spartakingdom** [comment]
They sending on you. 
![image](https://github.com/MeteorTheLizard/MMM_M9k_Remastered/assets/50296444/09142f6e-3b36-4733-8ddc-d4caca611278)

**Comment by Spartakingdom** [comment]
Just question is this addon works on the linux host?

**Comment by Spartakingdom** [comment]
Nvm when i use the steamworkshop then works.
